--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Valiant-Bedrock/libcommand
build-by-default: true
branches:
- master
projects:
  libcommand:
    model: virion
    type: library
...
