name: Continuous Integration
on: [push]
env:
  PHP_ARTIFACT_NAME: PHP-8.0-Linux-x86_64.tar.gz
  PHP_PATH: ./bin/php7/bin
  PHP_BINARY_PATH: ./bin/php7/bin/php
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download PHP
        run: wget "https://github.com/NetherGamesMC/php-build-scripts/releases/download/8.2/Linux.zip"
      - name: Unzip PHP
        run: unzip Linux.zip -d ./
      - name: Untar PHP
        run: tar -xzvf ${{ env.PHP_ARTIFACT_NAME }} -C ./
      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | ${{ env.PHP_BINARY_PATH }}
      - name: Install Composer dependencies
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{secrets.COMPOSER_AUTH_TOKEN}}"} }' # [tl! **]
        run: ${{ env.PHP_BINARY_PATH }} composer.phar install --prefer-dist --no-interaction
      # PHPStan
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze
      # Code style checks
      - name: Analyze code style
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff